#!/bin/bash

source "$CPU_PYTHON_V_ENV"

# Resetta l'OPTIND per evitare conflitti con altri script
OPTIND=1
EXEC_SCRIPT=0
while getopts ":s:" opt; do
    case $opt in
        s)
            echo "Executing Python script: $OPTARG"
            echo "Arguments: ${@:3}"
            python3 "$OPTARG" "${@:3}"
            EXEC_SCRIPT=1
            ;;
        # \?)
        #     # echo "Opzione non valida: -$OPTARG" "${@:1}"
        #     ;;
        :)
            echo "Opzione -$OPTARG richiede un argomento." "${@:1}"
            ;;
    esac
done

if [ $EXEC_SCRIPT -eq 0 ]; then
    # Passa il primo argomento come nome del file Python e tutti gli altri come argomenti
    python3 $CPU_PYTHON_DIR/elfConverter.py "${@:1}"
fi

deactivate
